### PR TITLE
Refactor index.js

### PR DESCRIPTION
**Pull request by max-hk**
This commit refactor index.js so it could be more easy to understand and maintain.

---

### Changelog

- Update dependencies
- Migrate to Webpack v4, replace pushstate-server with webpack-dev-server
- Organize functions to different files
- BREAKING CHANGE: not exporting xxx2xxx functions in index.js
- Revert 6e48ea8 as it break the demo
- All unused methods and variables are documented and removed in production builds (thanks to webpack tree shaking)
- Replace `var` with `const` and `let`
- Simplify code

---

### Notes

I tried to port util.js to external color conversion library (like chroma-js and @csstools/convert-color), but failed.

Reasons behind:

- `rgb2lab` is actually not a color converting function, it changes the color value.
- `lab2lch` returns accurate lightness and chroma values, but a "wrong"/modified hue value.

### CODE REVIEW

**Comment by maxloh** [comment]
To do:

- [ ] Check if `this` keyword is added to all function calls within the same class in `util.js` `[a-z][a-z][a-z]2[a-z][a-z][a-z]\(`
- [ ] Check if all functions are properly moved but not deleted
- [ ] Decide to keep `removed.js` or not (functions within that file are never called by other pieces of code)

**Comment by maxloh** [comment]
I have to revert https://github.com/eugeneford/material-palette-generator/commit/6e48ea8edc503b2d04f91947b2861544ec1fefa5, as the commit breaks the demo.

The current demo works because you haven't build it after that commit was introduced. (the live [bundle.js](https://github.com/eugeneford/material-palette-generator/blob/master/docs/bundle.js) was compiled 11 months ago).

**Comment by eugeneford** [comment]
@maxloh, sent a collaboration invite to you so that you can apply any changes that you consider worth doing

**Comment by maxloh** [comment]
> @maxloh, sent a collaboration invite to you so that you can apply any changes that you consider worth doing

Thx. I will complete the PR these few days.

**Comment by maxloh** [comment]
@eugeneford The pull request is now ready for review.

**Comment by max-hk** [comment]
It has been a week since a review is requested so I assume that the pull request is alright.

Just kindly revert the commit if you think it is not. :)

**Pull request merged**
